CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA(
idClinica SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeClinica VARCHAR (100) NOT NULL,
cnpj VARCHAR (20) NOT NULL,
endereco VARCHAR (250) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVeterinario SMALLINT PRIMARY KEY IDENTITY (1,1),
idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA (idClinica),
nomeVet VARCHAR (150)
);
GO



CREATE TABLE ATENDIMENTO(
idAtendimento SMALLINT PRIMARY KEY IDENTITY (1,1),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO (idVeterinario),
idPet SMALLINT FOREIGN KEY REFERENCES PETS (idPets) NOT NULL,
descricao VARCHAR (80) NOT NULL, 
dataAtendimento	 DATE NOT NULL
);
GO

CREATE TABLE DONO(
idDono SMALLINT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR (120) NOT NULL
);
GO

CREATE TABLE TIPOPET (
idTipoPet SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeTipoPet VARCHAR(200) UNIQUE
);
GO

CREATE TABLE RACA (
idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
idTipoPet SMALLINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
nomeRaca VARCHAR(200) UNIQUE
);
GO


CREATE TABLE PETS(
idPets SMALLINT PRIMARY KEY IDENTITY (1,1),
idRaca SMALLINT FOREIGN KEY REFERENCES RACA (idRaca),
idDono SMALLINT FOREIGN KEY REFERENCES DONOS (idDono),
nomePet  VARCHAR (30) NOT NULL
);
GO


