CREATE DATABASE PCLINICS;s
GO

USE PCLINICS;
GO

CREATE TABLE CLINICA(
idClinica SMALLINT PRIMARY KEY IDENTITY (1,1),
cnpj VARCHAR (20) NOT NULL,
endereco VARCHAR (250) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
idVeterinario SMALLINT PRIMARY KEY IDENTITY (1,1),
idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA (idClinica),
nomeVet VARCHAR (150)
);
GO

CREATE TABLE ATENDIMENTO(
idAtendimento SMALLINT PRIMARY KEY IDENTITY (1,1),
idVeterinario SMALLINT FOREIGN KEY REFERENCES VETERINARIO (idVeterinario),
idPet VARCHAR (50) NOT NULL,
descricao VARCHAR (80) NOT NULL, 
dataAtendimento	 DATE NOT NULL
);
GO

CREATE TABLE DONOS(
idDono SMALLINT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR (120) NOT NULL
);
GO


CREATE TABLE RACA (
	idRaca TINYINT PRIMARY KEY IDENTITY(1,1),
	idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
	nomeRaca VARCHAR(200) UNIQUE
);
GO


CREATE TABLE PETS(
idPets SMALLINT PRIMARY KEY IDENTITY (1,1),
idRaca TINYINT FOREIGN KEY REFERENCES RACA (idRaca),
iDono SMALLINT FOREIGN KEY REFERENCES DONOS (idDono),
nomePet  VARCHAR (30) NOT NULL
);
GO

CREATE TABLE TIPOPET (
	idTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoPet VARCHAR(200) UNIQUE
);
GO


