CREATE DATABASE EMPRESA_VEICULOS;
GO

USE EMPRESA_VEICULOS;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY IDENTiTY (1,1),
nomeEmpresa VARCHAR (15) NOT NULL
);

CREATE TABLE CLIENTE (
idCliente SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeCliente VARCHAR (65) NOT NULL,
cpf  VARCHAR (15) UNIQUE NOT NULL
);


CREATE TABLE MARCA(
idMarca SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeMarca VARCHAR (15) UNIQUE NOT NULL
);

CREATE TABLE MODELO(
idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(20) NOT  NULL
);

CREATE TABLE VEICULO(
idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
placa CHAR (8) UNIQUE NOT NULL 
);


CREATE TABLE ALUGUEL( 
idAluguel SMALLINT  PRIMARY KEY IDENTITY(1,1),
idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULO (idVeiculo),
idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE (idCliente),
dataRetirada DATE NOT NULL,
dataDevolucao DATE NOT NULL
);

