CREATE DATABASE EMPRESA_VEICULOS;
GO

USE EMPRESA_VEICULOS;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY REFERENCES EMPRESA(idEmpresa),
);

CREATE TABLE VEICULO(
idVeiculos SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeVeiculos VARCHAR (8) NOT NULL,
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo VARCHAR (256) NOT NULL
);
