CREATE DATABASE EMPRESA_VEICULOS;
GO

USE EMPRESA_VEICULOS;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY REFERENCES EMPRESA(idEmpresa),
nomeEmpresa VARCHAR (15) NOT NULL
);


CREATE TABLE VEICULO(
idVeiculos SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeVeiculos VARCHAR (8) NOT NULL,
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo VARCHAR (256) NOT NULL
);

CREATE TABLE ALUGUEIS( 
idAluguel SMALLINT  PRIMARY KEY IDENTITY(1,1),
idModelo Varchar (256),
idCliente SMALLINT PRIMARY KEY IDENTITY(1,1)
);

CREATE TABLE MODELOS(
idModelo SMALLINT PRIMRY KEY IDENTITY(1,1),
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
idVeiculo SMALLINT FOREING KEY REFERENCES VEICULO (idVeiculo),
nomeModelo VARCHAR(20) NOT  NULL
);

ALTER TABLE VEICULO
ADD idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo)
