CREATE DATABASE EMPRESA_VEICULOS;
GO

USE EMPRESA_VEICULOS;
GO

CREATE TABLE EMPRESA(
idEmpresa SMALLINT PRIMARY KEY REFERENCES EMPRESA(idEmpresa),
nomeEmpresa VARCHAR (15) NOT NULL
);

CREATE TABLE MARCA(
idMarca SMALLINT PRIMARY KEY IDENTITY (1,1),
nomeMarca VARCHAR (15) UNIQUE NOT NULL
);

CREATE TABLE MODELOS(
idModelo SMALLINT PRIMARY KEY IDENTITY(1,1),
idMarca SMALLINT FOREIGN KEY REFERENCES MARCA(idMarca),
nomeModelo VARCHAR(20) NOT  NULL
);

CREATE TABLE VEICULO(
idVeiculo SMALLINT PRIMARY KEY IDENTITY(1,1),
nomeVeiculos VARCHAR (8) NOT NULL,
idEmpresa SMALLINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
);


CREATE TABLE ALUGUEIS( 
idAluguel SMALLINT  PRIMARY KEY IDENTITY(1,1),
idModelo Varchar (256),
idCliente SMALLINT FOREIGN KEY REFERENCES CLIENTE (idCliente)
);

